# 📌 Broadcasting
- shape이 달라도 연산이 가능하다
    - 뒷 차원부터 비교하여 같으면 연산 가능
    - 예시) (4,3)과 (3,) (1,3)은 연산 가능/ (4,)은 불가능

# Boolean indexing

In [5]:
import numpy as np
x = np.random.randint(1,10, size=5)
print(x)

[1 1 9 3 2]


In [7]:
even_mask = x % 2 ==0
print(even_mask)
print(x[even_mask])
print(x[x % 2 ==0])

[False False False False  True]
[2]
[2]


In [9]:
x[(x<3) | (x%2==0)]

array([1, 1, 2])

# linalg

In [16]:
x = np.random.rand(3,3)
print(x)
print(x@np.linalg.inv(x))

[[0.27265109 0.37527036 0.07952165]
 [0.73876621 0.9114253  0.36237283]
 [0.87169105 0.26181831 0.10202879]]
[[ 1.00000000e+00  5.55111512e-17  5.55111512e-17]
 [-8.88178420e-16  1.00000000e+00  1.94289029e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [18]:
a = np.array([[1,1],[2,4]])
b = np.array([25,64])

x = np.linalg.solve(a, b)
print(x)
np.allclose(a@x, b)

[18.  7.]


True