# Numpy 장점
- 성능: 파이썬 리스트보다 빠름
- 메모리: 파이썬 리스트보다 적은 메모리 사용
    - 더 많은 데이터를 한 번에 로딩할 수 있다.
- 다양한 빌트인 함수: 선형대수, 통계 관련 여러 함수 내장


# ndarray
- c언어로 구현되어 빠르다.
- 생성되는 원소들이 연속적인 메모리에 잡힌다.
    - 순회하거나 연산 반복할때 빠르게 적용 가능
- vectorization: 전체 데이터에 대해 한 묶음으로 연산 가능

반면, python list는
- 연속되지 않은 메모리
- 명시적인 loop 사용한다.

## ndarray 생성

In [4]:
import numpy as np
import matplotlib.pyplot as plt

y = np.array([1,2,3,4])
x = np.arange(1,10,2)


In [6]:
np.ones((4, 5)) # 튜플

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.zeros((2,1,3))

array([[[0., 0., 0.]],

       [[0., 0., 0.]]])

In [8]:
np.empty((1,2))

array([[1.49166815e-154, 1.49166815e-154]])

In [14]:
np.full((1,2), 10)

array([[10, 10]])

In [15]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

### 단위 행렬 생성

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 차원 변경

In [18]:
x = np.arange(1,16)
print(x)
x.shape # 튜플로 표현, 1차원
x.reshape(3,5) # 3행 5열 행렬

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### ramdom 값 생성
- np.random.rand
- np.random.randn
- np.random.randint
- np.random.seed
    - random 값을 동일하게 다시 생성하고자 할 때
    - np.random.seed()를 먼저 호출하고 random 호출
- np.random.choice
    - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링

In [19]:
np.random.rand(2,3) # 0과 1사이 random 값 생성

array([[0.2806412 , 0.8466291 , 0.33193376],
       [0.97561126, 0.16082809, 0.44893584]])

In [20]:
# 정규분포 (normal distribution)
np.random.randn(3,4)

array([[ 0.09805528,  0.43018371,  1.86891645,  0.15643157],
       [ 0.03603306, -0.78722194, -0.67811373, -0.91898264],
       [ 0.32995986,  2.06583911, -1.56260721,  0.63410236]])

In [21]:
# 정수 
np.random.randint(1,10,size=(5,))

array([5, 1, 8, 9, 9])

In [23]:
# seed 함수
np.random.seed(1)
np.random.randint(1,10,size=(5,))

array([6, 9, 6, 1, 1])

In [24]:
# choic: 특정 데이터에서 샘플링 할 때
np.random.choice(100, size=(1,2), replace=True)

array([[ 1, 76]])

In [25]:
# 특정 확률 분포에서 샘플링 할 때
np.random.normal(size = (1,2))

array([[ 1.5827523 , -1.04514683]])